export enum COMPLAINT_STATUS {
  PENDING = 'PENDING',
  ACKNOWLEDGED = 'ACKNOWLEDGED',
  IN_PROGRESS = 'IN_PROGRESS',
  RESOLVED = 'RESOLVED',
  REJECTED = 'REJECTED',
  CLOSED = 'CLOSED'
}

export enum COMPLAINT_CATEGORY {
  ROADS = 'ROADS',
  WATER = 'WATER',
  ELECTRICITY = 'ELECTRICITY',
  SANITATION = 'SANITATION',
  PUBLIC_SAFETY = 'PUBLIC_SAFETY',
  TRANSPORTATION = 'TRANSPORTATION',
  OTHER = 'OTHER'
}

export const STATUS_TRANSITIONS: Record<COMPLAINT_STATUS, COMPLAINT_STATUS[]> = {
  [COMPLAINT_STATUS.PENDING]: [COMPLAINT_STATUS.ACKNOWLEDGED, COMPLAINT_STATUS.REJECTED],
  [COMPLAINT_STATUS.ACKNOWLEDGED]: [COMPLAINT_STATUS.IN_PROGRESS, COMPLAINT_STATUS.REJECTED],
  [COMPLAINT_STATUS.IN_PROGRESS]: [COMPLAINT_STATUS.RESOLVED, COMPLAINT_STATUS.PENDING],
  [COMPLAINT_STATUS.RESOLVED]: [COMPLAINT_STATUS.CLOSED, COMPLAINT_STATUS.IN_PROGRESS],
  [COMPLAINT_STATUS.REJECTED]: [COMPLAINT_STATUS.CLOSED, COMPLAINT_STATUS.PENDING],
  [COMPLAINT_STATUS.CLOSED]: []
};

export const STATUS_LABELS: Record<COMPLAINT_STATUS, string> = {
  [COMPLAINT_STATUS.PENDING]: 'Pending Analysis',
  [COMPLAINT_STATUS.ACKNOWLEDGED]: 'Acknowledged',
  [COMPLAINT_STATUS.IN_PROGRESS]: 'In Progress',
  [COMPLAINT_STATUS.RESOLVED]: 'Resolved',
  [COMPLAINT_STATUS.REJECTED]: 'Rejected',
  [COMPLAINT_STATUS.CLOSED]: 'Closed'
};

export const CATEGORY_LABELS: Record<COMPLAINT_CATEGORY, string> = {
  [COMPLAINT_CATEGORY.ROADS]: 'Roads & Infrastructure',
  [COMPLAINT_CATEGORY.WATER]: 'Water Supply',
  [COMPLAINT_CATEGORY.ELECTRICITY]: 'Power & Electricity',
  [COMPLAINT_CATEGORY.SANITATION]: 'Waste & Sanitation',
  [COMPLAINT_CATEGORY.PUBLIC_SAFETY]: 'Public Safety',
  [COMPLAINT_CATEGORY.TRANSPORTATION]: 'Transportation',
  [COMPLAINT_CATEGORY.OTHER]: 'Other Issues'
};

export const STATUS_COLORS: Record<COMPLAINT_STATUS, string> = {
  [COMPLAINT_STATUS.PENDING]: 'bg-yellow-500',
  [COMPLAINT_STATUS.ACKNOWLEDGED]: 'bg-blue-500',
  [COMPLAINT_STATUS.IN_PROGRESS]: 'bg-purple-500',
  [COMPLAINT_STATUS.RESOLVED]: 'bg-green-500',
  [COMPLAINT_STATUS.REJECTED]: 'bg-red-500',
  [COMPLAINT_STATUS.CLOSED]: 'bg-gray-500'
};
